name: MLSecOps - SLSA Build Track L2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-generate:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      attestations: write
      artifact-metadata: write

    steps:
      - name: Source code checkout
        uses: actions/checkout@v7

      - name: Python Setup
        uses: actions/setup-python@v7
        with:
          python-version: '3.10'
        
      - name: Training simulation and ML-BOM generation
        run: |
          python mock_train.py

      - name: ML-BOM attestation generation
        uses: actions/attest@v4
        with:
          subject-path: 'yolo_trained_model.pt'
          sbom-path: 'mlbom.json'

      - name: SLSA Provenance generation
        uses: actions/attest@v4
        with:
          subject-path: |
            yolo_trained_model.pt
            mlbom.json

      - name: Artifact upload
        uses: actions/upload-artifact@v7
        with:
          name: ml-artifacts
          path: |
            yolo_trained_model.pt
            mlbom.json
